obj-$(CONFIG_SH_DMAE_BASE) += shdma-base.o
obj-$(CONFIG_SH_DMAE) += shdma.o
obj-$(CONFIG_SH_DMAE_DESC) += shdma-desc.o
obj-$(CONFIG_SH_DMAEPP_BASE) += shdmapp-base.o
obj-$(CONFIG_SH_DMAEPP_AUPP) += audma-pp.o
