#define SGX_FEATURE_MP_CORE_COUNT 2
#define SUPPORT_EXTENSION_REL 
#define ENABLE_REL_STD_0001 
#define DEBUG_LINUX_MEMORY_ALLOCATIONS 
#define SUPPORT_GET_MEMINFO 
#define DEBUG_LINUX_MEMORY_ALLOCATIONS 
#define ENABLE_REL_STD_0016 
#define LINUX 
#define PVR_BUILD_DIR "r8a7791_linux"
#define PVR_BUILD_TYPE "release"
#define PVRSRV_MODNAME "pvrsrvkm"
#define SGXCORE 544
#define SGX544 
#define SUPPORT_SGX544 
#define SUPPORT_SGX 
#define SGX_CORE_REV 115
#define TRANSFER_QUEUE 
#define PVR_SECURE_HANDLES 
#define DISPLAY_CONTROLLER dc_linuxfb
#define PVR_LINUX_MEM_AREA_POOL_MAX_PAGES 0
#define RELEASE 
#define SUPPORT_PERCONTEXT_PB 
#define SUPPORT_HW_RECOVERY 
#define SUPPORT_SGX_HWPERF 
#define SUPPORT_SGX_LOW_LATENCY_SCHEDULING 
#define SUPPORT_SGX_NEW_STATUS_VALS 
#define SUPPORT_DBGDRV_EVENT_OBJECTS 
#define SGX_FEATURE_SYSTEM_CACHE 
#define SGX_FEATURE_MP 
#define SYS_USING_INTERRUPTS 
#define SUPPORT_PVRSRV_DEVICE_CLASS 
#define SUPPORT_PVRSRV_GET_DC_SYSTEM_BUFFER 
#define IMG_ADDRSPACE_PHYSADDR_BITS 32
#define SUPPORT_LINUX_X86_WRITECOMBINE 
#define SUPPORT_LINUX_X86_PAT 
#define SYS_SGX_ACTIVE_POWER_LATENCY_MS 100
#define SYS_CUSTOM_POWERLOCK_WRAP 
#define PVR_LINUX_USING_WORKQUEUES 
#define PVR_LINUX_MISR_USING_PRIVATE_WORKQUEUE 
#define PVR_LINUX_TIMERS_USING_WORKQUEUES 
#define LDM_PLATFORM 
#define PVR_LDM_PLATFORM_PRE_REGISTERED 
#define PVR_LDM_DRIVER_REGISTRATION_NAME "pvrsrvkm"
#define SOC_NAME "r8a7791"
#define SYS_SGX_REG_BASE 0xfce00000
#define SYS_SGX_IRQ 0x59
#define SYS_SGX_CLOCK_SPEED 520000000
#define SUPPORT_FIXED_DEVICE_MEMORY 1
#define USE_LINUX_CLK_FRAMEWORK 
#define DISPLAY_DEVICE_COUNT 8
#define XPROC_WORKAROUND_NUM_SHAREABLES 4095
